version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd clothing‑store
      - npm install  # or npm install
  build:
    commands:
      - echo "Starting build..."
      - set -e
      - npm run build
      - echo "Build completed. Listing output directory:"
      - ls -al
      - cd ..
      - ls -al build
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g, React app)
  discard-paths: yes
